### PR TITLE
Create and update android.yml for ci

### PR DESCRIPTION
**Pull request by MatteoGheza**

### CODE REVIEW

**Comment by ghost** [comment]
This method will provide the apk file in a debug version as a release, while the releases have the digital signature and have to be build separately.

**Comment by MatteoGheza** [comment]
Yes, but it works for every commit for testing

**Comment by MatteoGheza** [comment]
This is not for release

**Comment by ghost** [comment]
So where the apk will be saved?

**Comment by MatteoGheza** [comment]
In artifact list

**Comment by MatteoGheza** [comment]
In every github action page

**Pull request merged**
