### PR TITLE
Create android.yml for ci/cd

### PR DESCRIPTION
**Pull request by MatteoGheza**
For ci/cd testing and auto apk building

### CODE REVIEW

**Comment by MatteoGheza** [comment]
P.S: @bonsky97 I'm working on auto update feature. Stay tuned!

**Comment by massimopagani** [comment]
It's a great idea then the problem would be to implement it in the graphical interface of the app

**Comment by ghost** [comment]
Thank you for your work Matteo Gheza, can you plaese contact me on email at lorenzodauria97@gmail.com to talk about what you are working on?

**Comment by MatteoGheza** [comment]
> Thank you for your work Matteo Gheza, can you plaese contact me on email at lorenzodauria97@gmail.com to talk about what you are working on?

Ok

**Comment by ghost** [comment]
Thanks! Integrated manually

**Pull request closed without merging**
